# Generated by Django 4.1.7 on 2023-04-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='cat_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
