# Generated by Django 4.1.7 on 2023-04-10 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_alter_categorymodel_cat_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='cat_img',
        ),
    ]
