# Generated by Django 4.1.7 on 2023-04-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_remove_categorymodel_cat_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventpack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('des', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menupack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('des', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
