# Generated by Django 4.1.7 on 2023-04-10 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0006_eventpack_menupack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Venue', models.CharField(max_length=255)),
                ('number_of_persons', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('eventpack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.eventpack')),
                ('menupack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.menupack')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
