# Generated by Django 4.1.7 on 2023-04-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_eventbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='Venue',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='number_of_persons',
            field=models.CharField(max_length=200),
        ),
    ]
