# Generated by Django 4.1.7 on 2023-04-10 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_alter_eventbooking_venue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Venue', models.CharField(max_length=300)),
                ('number_of_persons', models.CharField(max_length=200)),
                ('eventpack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.eventpack')),
                ('menupack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.menupack')),
            ],
        ),
        migrations.DeleteModel(
            name='Eventbooking',
        ),
    ]
