# Generated by Django 4.1.7 on 2023-04-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_eventbooking_delete_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventbooking',
        ),
    ]
