# Generated by Django 4.1.7 on 2023-04-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_eventbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventbooking',
        ),
    ]
