# Generated by Django 4.1.7 on 2023-04-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_delete_eventbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpack',
            name='des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menupack',
            name='des',
            field=models.TextField(),
        ),
    ]
