# Generated by Django 4.1.7 on 2023-04-10 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_alter_eventpack_des_alter_menupack_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('people', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('eventpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.eventpack')),
                ('menupack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.menupack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.customermodel')),
            ],
        ),
    ]
