# Generated by Django 4.1.7 on 2023-04-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_eventbooking_amount_eventbooking_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='amount',
            field=models.CharField(max_length=255),
        ),
    ]
